version: '3.8'

services:
  php-apache-environment:
    build:
      context: ./php
      dockerfile: Dockerfile

    container_name: redlock-web-2.0
    image: redlock-web-2.0:latest
    
    ports:
    - 7077:80


  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile

    container_name: redlock-db-dlv
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always

    environment:
        MYSQL_ROOT_PASSWORD: ZeroAtmosphere8744736
        MYSQL_DATABASE: redlock-db
        MYSQL_USER: Creator
        MYSQL_PASSWORD: ZeroAtmosphere8744736

    ports:
        - 4848:3306